services:
  postgres:
    env_file:
      - .env
    image: postgres:16.6-alpine
    container_name: ${DB_HOST}
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: always
    networks:
      - standalone-database
    shm_size: 128mb
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_HOST}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    restart: always
    networks:
      - standalone-database

  redis:
    image: redis:7.4.1-alpine
    container_name: ${REDIS_HOST}
    # command: redis-server /usr/local/etc/redis/redis.conf
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - .data/redis:/var/lib/redis
      - .data/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - standalone-database

networks:
  standalone-database: