# version: '3.9'

services:
  postgres:
    env_file:
      - .env
    image: postgres:16.6-alpine
    container_name: ${DB_HOST}
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_HOST}
    environment:
      # WAIT_HOSTS: ${DB_HOST}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    restart: always

  redis:
    image: redis:7.4.1-alpine
    container_name: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
