CREATE TABLE tbl_users (
  id BIGINT PRIMARY KEY,
  username VARCHAR (30) NULL,
  email VARCHAR (50) UNIQUE NOT NULL,
  password VARCHAR (50) NOT NULL,
  status VARCHAR (20) NOT NULL DEFAULT 'APPROVED',
  last_login TIMESTAMP,
  url_limit INTEGER NOT NULL DEFAULT 100,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbl_urls (
    id VARCHAR (10) PRIMARY KEY,
    original_url TEXT NOT NULL,
    user_id BIGINT,
    clicks INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user
      FOREIGN KEY(user_id)
        REFERENCES tbl_users(id)
);
